### ISSUE TITLE
Enable interpolation inside strings

### ISSUE THREAD

**Issue by ccprog** [ccprog/markdown-it-shortcode-tag#2]
This would come with a slight change to unquoted interpolation syntax. For the sake of consistency, both cases should use

    <image src="${path}/icon.png">
    <image src=${url}>

String interpolation would from my viewpoint not need a custom interpolator function.

this is a follow-up to https://github.com/ccprog/markdown-it-shortcode-tag/pull/1

**Comment by ccprog** [comment]
To state it again, I am quite flexible as to use `#{}` (Sass-like), `${}` (ES6-like) or `{{}}` (Angular-like), but would strongly prefer not to introduce seperate syntax for string and object interpolation.

**Comment by aneilbaboo** [comment]
Copied over from #1:

For my specific use case, I'd prefer simple braces, partly because I prefer something minimal for end users, and because I'd like to compose Markdown in code with ES6 style templates, so this syntax won't work in that case.

What do you think of using Angular's syntax for string interpolation? This provides React syntax for attributes and Angular syntax for strings, so will look familiar:

```javascript
<CustomMap geos={geos} title="{{name}}'s Custom Map" />
```

The attribute parser won't misidentify the inner braces of `{{name}}` as long as `reAttrs` places the the string regex before the attribute regex (as it is in this PR).

**Comment by aneilbaboo** [comment]
Sorry, I misunderstood. I thought you wanted to have two different syntaxes.  I'm fine with either Angular or Sass style:

```javascript
<CustomMap geos={{geos}} title="{{name}}'s Custom Map" />
```
Or
```javascript
<CustomMap geos=#{geos} title="#{name}'s Custom Map" />
```
